### ISSUE TITLE
Error in setting up after installation.

### ISSUE THREAD

**Issue by gllmlbrt** [vlebourl/custom_biketrax#3]
Installation went great, sign-in all good. on set-up following error and log:

`2022-08-08 09:00:38.186 INFO (MainThread) [homeassistant.setup] Setting up biketrax
2022-08-08 09:00:38.187 INFO (MainThread) [homeassistant.setup] Setup of domain biketrax took 0.0 seconds
2022-08-08 09:00:39.004 ERROR (MainThread) [custom_components.biketrax] Unexpected error fetching biketrax coordinator data: 'Device' object has no attribute 'bike_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/biketrax/coordinator.py", line 27, in _async_update_data
    devices: dict[str, Device] = {d.bike_id: d for d in self.client.devices}
  File "/config/custom_components/biketrax/coordinator.py", line 27, in <dictcomp>
    devices: dict[str, Device] = {d.bike_id: d for d in self.client.devices}
AttributeError: 'Device' object has no attribute 'bike_id'
2022-08-08 09:00:39.005 WARNING (MainThread) [homeassistant.config_entries] Config entry '<email>' for biketrax integration not ready yet: 'Device' object has no attribute 'bike_id'; Retrying in background
2022-08-08 09:00:39.008 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=biketrax>`

**Comment by vlebourl** [comment]
Hi, this integration is actually not under development as it's covered by https://github.com/basilfx/homeassistant-biketrax

I'll update the readme to make it clear. 
cheers
